name: Azure Pages CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master


jobs:
  build_and_deploy_job:
    env:
      APP_LOCATION: ""
      API_LOCATION: "api"
      APP_ARTIFACT_LOCATION: "dist"
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v1
      - name: Build And Deploy
        id: builddeploy
        uses: joslinmicrosoft/staticsitesactionoryx@canary3
        with:
          azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN_ASHY_FOREST_076F61E4 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: ${process.env.APP_LOCATION} # App Source Code Path
          api_location: process.env.API_LOCATION # Api Source Code Path - optional
          app_artifact_location: process.env.APP_ARTIFACT_LOCATION # Built App Content Directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: joslinmicrosoft/staticsitesaction@canary2
        with:
          azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN_ASHY_FOREST_076F61E4 }}
          action: "close"
